### ISSUE TITLE
Downloads not necessary dependencies

### ISSUE THREAD

**Issue by saklar13** [youngquan/pip-download#1]
The tool downloads dependencies for my current OS and Python version besides that I specified.

For example, I run the command to download dependencies for Windows and Python 2.7 on Linux machine with Python 3.7
```
$ pip-download -s "win" -py cp27 -i https://pypi.org/simple cryptography
$ ls .

cffi-1.13.0-cp27-cp27m-win32.whl      cffi-1.13.0-cp37-cp37m-manylinux1_x86_64.whl  cryptography-2.8-cp27-cp27m-win32.whl      cryptography-2.8-cp34-abi3-manylinux2010_x86_64.whl  pycparser-2.19.tar.gz            six-1.12.0.tar.gz
cffi-1.13.0-cp27-cp27m-win_amd64.whl  cffi-1.13.0.tar.gz                            cryptography-2.8-cp27-cp27m-win_amd64.whl  cryptography-2.8.tar.gz                              six-1.12.0-py2.py3-none-any.whl
```

**Comment by jayvdb** [comment]
cffi is a dependency of the source tarball `cryptography-2.8.tar.gz` which was downloaded.

**Comment by saklar13** [comment]
Yes, the package should download `cffi-1.13.0-cp27-cp27m-win32.whl`, `cffi-1.13.0-cp27-cp27m-win_amd64.whl` and `cffi-1.13.0.tar.gz`. But it also downloads `cffi-1.13.0-cp37-cp37m-manylinux1_x86_64.whl` for python version 3.7 and linux platform

**Comment by youngquan** [comment]
@saklar13 you can try again, now cffi-1.13.0-cp37-cp37m-manylinux1_x86_64.whl will not be download.
