### ISSUE TITLE
Respect pip config

### ISSUE THREAD

**Issue by pawamoy** [youngquan/pip-download#24]
Following #5, I'm working in a corporate environment and we use a private pypi mirror. Would it be possible for *pip-download* to respect pip's config so I don't have to manually specify the index-url on the command line?

Or maybe I can configure this in *pip-download* JSON configuration file?

Also, thank you very much for this tool, it is highly convenient!!

**Comment by youngquan** [comment]
Got it! How about this priorities：pip's config which have been configured > the time zone > pypi.org？I also think the way using the time zone  to pick the pypi index should be optimized or be removed. Do you have some idea?

**Comment by pawamoy** [comment]
Thans for the quick answer 🙂 

For the priority, I'd say:

1. pip's config (if it exists and index-url is set)
2. time zone
3. pypi.org

I personally never needed another public mirror than pypi.org, so I can't say if the time-zone-based approach is good or not, I'll let you decide!

For reference, here's my pip config file:

```ini
[global]
trusted-host = our-private-index.domain.com
index-url = https://username:password@our-private-index.domain.com/index/simple/
cert = /home/user/certs/ca-bundle.crt
```

Not sure what internals you are using, and therefore if you could just read `index-url` (note the credentials in it for basic auth) or would have to read the rest as well, like `trusted-host` and `cert`.

Let me know if I can be of any help 🙂

**Comment by di** [comment]
This is probably blocked on https://github.com/di/pip-api/issues/44.

**Comment by pawamoy** [comment]
In the end I'll close this because it's very easy to set up an alias with the right index. Feel free to reopen if you think it is still an interesting feature!
