### ISSUE TITLE
求更新，发现了好多问题

### ISSUE THREAD

**Issue by zhaozhaofox** [youngquan/pip-download#32]
我在指定了Python的版本，比如 3.6，但是下载的包是最新的，打开包的PYPI页面，可以很明显看到要求是 >= 3.8。好像单纯从包名很难区分支持的Python版本。比如 py3-none，但实际确实只有 python >= 3.8

**Comment by youngquan** [comment]
Hello, thanks for your feedback. Can you provide the command you're using and the output from the Terminal or Console.

**Comment by youngquan** [comment]
Sorry, if you could not provide more details, I have to close the issue. However, feel free to reply at anytime.
