### ISSUE TITLE
Add an option to not display progress bars.

### ISSUE THREAD

**Issue by gcoakes** [youngquan/pip-download#4]
I am trying to use this in a pipeline which will mirror the dependencies from a requirements.txt to a local pypiserver. I would like the option to disable progress bars because they fill up the logs in my CI/CD pipeline. Is this feasible?

**Comment by youngquan** [comment]
ok, I will try to add an option like --slient tonight maybe.

**Comment by youngquan** [comment]
you can try `--quiet` or `-q`.

**Comment by gcoakes** [comment]
Thank you for this. I had been using a dirty hack to remove the logging, but now I can go back to mainline.
