### ISSUE TITLE
Default pypi index

### ISSUE THREAD

**Issue by jayvdb** [youngquan/pip-download#5]
When I run pip-download without specifying an index, it defaults to PyPI index https://mirrors.tuna.tsinghua.edu.cn/ .

It doesnt tell me why that one was chosen.

`python3 -m pipdownload --help` should mention that it is the default.

And it should choose pypi.org as the default unless it is overridden with a config var, or 'is china' detects problems with pypi.org

**Comment by youngquan** [comment]
You are right. I never thought this package would be used by someone else except myself，so some config was chosen all for my convenience. I will fix this tonight maybe.😁

**Comment by youngquan** [comment]
use  pypi.org as the default pypi index, and use tzlocal to determine the time zone.
